package org.divxdede.swing.busy.sample;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import org.divxdede.swing.busy.BusyModel;
import org.divxdede.swing.busy.FutureBusyModel;

/**
 *
 * @author  Administrator
 */
public class BusySampleFrame extends javax.swing.JFrame {

    ExecutorService service = Executors.newSingleThreadExecutor();
    
    /** Creates new form BusySampleFrame */
    public BusySampleFrame() {
        initComponents();
        
        /** Create our model
         */
        BusyModel model = new FutureBusyModel();
        model.setDeterminate(true);
        model.setCancellable(true);
        this.jBusyComponent.setBusyModel(model);
        
        this.jBusyComponent2.getBusyModel().setCancellable(true);
        this.jBusyComponent2.getBusyModel().setDeterminate(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXGraph1 = new org.jdesktop.swingx.JXGraph();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jBusyComponent = new org.divxdede.swing.busy.JBusyComponent();
        jBusyComponent2 = new org.divxdede.swing.busy.JBusyComponent();
        jButton2 = new javax.swing.JButton();
        jBusyComponent3 = new org.divxdede.swing.busy.JBusyComponent();
        jButtonWaitAWhile = new javax.swing.JButton();

        jXGraph1.setBackground(new java.awt.Color(240, 227, 187));

        org.jdesktop.layout.GroupLayout jXGraph1Layout = new org.jdesktop.layout.GroupLayout(jXGraph1);
        jXGraph1.setLayout(jXGraph1Layout);
        jXGraph1Layout.setHorizontalGroup(
            jXGraph1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 410, Short.MAX_VALUE)
        );
        jXGraph1Layout.setVerticalGroup(
            jXGraph1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 290, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Print (Track a cancellable job)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Petterson", new Integer(23), "USA"},
                {"Dupont", new Integer(33), "France"},
                {"Marelli", new Integer(16), "Italy"},
                {"Markhoff", new Integer(45), "Russia"}
            },
            new String [] {
                "Name", "Age", "Country"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(100);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BusySample");

        jBusyComponent.setView(jPanel1);

        jBusyComponent2.setView(jScrollPane2);

        jButton2.setText("Go infinite job (but cancellable)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBusyComponent3.setView(jXGraph1);

        jButtonWaitAWhile.setText("Wait a while");
        jButtonWaitAWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWaitAWhileActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jBusyComponent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jBusyComponent2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButtonWaitAWhile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .add(jBusyComponent3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jBusyComponent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jBusyComponent3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 290, Short.MAX_VALUE)
                    .add(jBusyComponent2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 290, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButtonWaitAWhile))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        this.jBusyComponent.getBusyModel().setMinimum(0);
        this.jBusyComponent.getBusyModel().setMaximum(100);
        this.jBusyComponent.getBusyModel().setValue(0);
        
        Runnable doRun = new Runnable() {
            public void run() {
                int value = 0;
                while( value < 100 ) {
                    if( Thread.currentThread().isInterrupted() ) {
                        System.out.println("Interrupted");
                        break;
                    }
                    
                    try {
                        Thread.sleep(75);
                        value++;
                    }
                    catch(InterruptedException ie) {
                        System.out.println("Interrupted");
                        break;
                    }
                    catch(Exception e) {
                        e.printStackTrace();
                    }
                    jBusyComponent.getBusyModel().setValue(value);
                }
            }
        };
        Future future = service.submit(doRun);
        ((FutureBusyModel)this.jBusyComponent.getBusyModel()).setFuture(future);
        ((FutureBusyModel)this.jBusyComponent.getBusyModel()).setDeterminate(true); // determinate
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jBusyComponent2.getBusyModel().setBusy(true);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButtonWaitAWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWaitAWhileActionPerformed
        this.jBusyComponent3.getBusyModel().setBusy(true);
        Runnable doRun = new Runnable() {
            public void run() {
                try {
                    Thread.sleep(3000);
                }
                catch(Exception e) {
                    e.printStackTrace();
                }
                jBusyComponent3.getBusyModel().setBusy(false);
            }
        };
        Thread t = new Thread(doRun);
        t.start();
}//GEN-LAST:event_jButtonWaitAWhileActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    LookAndFeel laf = (LookAndFeel)Class.forName( UIManager.getSystemLookAndFeelClassName() ).newInstance();
                    UIManager.setLookAndFeel( laf );
                }
                catch(Exception e) {
                    e.printStackTrace();
                }
                BusySampleFrame bsf = new BusySampleFrame();
                bsf.setLocationRelativeTo(null);
                bsf.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.divxdede.swing.busy.JBusyComponent jBusyComponent;
    private org.divxdede.swing.busy.JBusyComponent jBusyComponent2;
    private org.divxdede.swing.busy.JBusyComponent jBusyComponent3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonWaitAWhile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private org.jdesktop.swingx.JXGraph jXGraph1;
    // End of variables declaration//GEN-END:variables

}
