package org.divxdede.swing;

import java.awt.Color;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import javax.swing.JTable;
import javax.swing.JTree;
import org.divxdede.swing.busy.DefaultBusyModel;
import org.divxdede.swing.busy.FutureBusyModel;
import org.divxdede.swing.busy.JBusyComponent;

/**
 *
 * @author  Administrator
 */
public class BusySample extends javax.swing.JFrame {

    /** Creates new form BusySample */
    public BusySample() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);
        jScrollPane1.setViewportView( new JBusyComponent<JTable>(jTable) );

        jScrollPane2.setViewportView(jTree1);
        jScrollPane2.setViewportView( new JBusyComponent<JTree>(jTree1) );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 407, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        final BusySample form = new BusySample();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form.setVisible(true);
            }
        });
        
        try {
            final JBusyComponent jbc = (JBusyComponent)form.jScrollPane1.getViewport().getView();
            final JBusyComponent jbc2 = (JBusyComponent)form.jScrollPane2.getViewport().getView();
            
            
            FutureBusyModel model = new FutureBusyModel();
            
            jbc.setBusyModel( model );
            jbc2.setBusyModel( model );
            Thread.sleep(1500);
            model.setBusy(true);
            Thread.sleep(5000);
            
            Runnable doRun = new Runnable() {
                public void run() {
                    try {
                        jbc.getBusyModel().setMinimum(500);
                        jbc.getBusyModel().setMaximum(1000);
                        jbc.getBusyModel().setValue(500);
                        jbc.getBusyModel().setDeterminate(true);
                        ((DefaultBusyModel)jbc.getBusyModel()).setAutoCompletionEnabled(true);;
                        for(int value = 500 ; value <= 1000 ; value++ ) {
                            if( Thread.currentThread().isInterrupted() ) throw new InterruptedException();
                            jbc.getBusyModel().setValue(value);
                            Thread.sleep(20);
                            if( value == 750 ) form.jTable.setBackground( Color.YELLOW );
                        }
                    }
                    catch( InterruptedException ie ) {
                        System.out.println("CANCELLED");
                    }
                    catch(Exception e) {
                        e.printStackTrace();
                    }
                }
            };
            
            ExecutorService service = Executors.newSingleThreadExecutor();
            Future future = service.submit(doRun);
            model.setFuture( future  );
            try {
                future.get();
            }
            catch(Exception e) {
                e.printStackTrace();
            }
//            jbc.getBusyModel().setDeterminate(false);
//            jbc.getBusyModel().setBusy(true);
            System.out.println("completed");
        }
        catch(Exception e) { e.printStackTrace(); }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

}
